# Change these first
owner: Yurasubs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Yurasubs
    url: https://www.yurasu.xyz/    
    expectedStatusCodes:
      - 304
      - 403
  - name: RDP Yura
    url: $RDPYURA
  - name: Backup Web
    url: $BACKUPWEB
    expectedStatusCodes:
      - 304
      - 403
  - name: Discord Websocket
    url: https://gateway.discord.gg/
    check: "tcp-ping"

status-website:
  cname: status.yurasu.xyz
  logoUrl: https://blogger.googleusercontent.com/img/a/AVvXsEjbvXvBf1H8AnWvTksSwrSRxxP0E2tT2qKNkD3IdLsYEmZ6a7vaWppQXv12BElgdL3EcSTB-C83c3-dufIfbMebheyJa5a4ehzi3qSvlR5R6hDa8z_YWzHMc9b2XZx5EY9y1PtXAfQ3XMKFS55_24bJW62QfRtaZrmQjAzEY84ZXSAGlnW14Ab0VLm2bg
  name: Yuramedia Link
  theme: dark
  favicon: https://www.yurasu.xyz/favicon.ico
  
